[platformio]
src_dir = firmware/PoudreTrailCYD/src
include_dir = firmware/PoudreTrailCYD/include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI
  paulstoffregen/XPT2046_Touchscreen
